In [1]:
import sys

from evoman.environment import Environment
from demo_controller import player_controller

# imports other libs
import time
import numpy as np
from math import fabs,sqrt
import glob, os
from numpy import random

pygame 2.5.2 (SDL 2.28.3, Python 3.11.4)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
# choose this for not using visuals and thus making experiments faster
headless = True
if headless:
    os.environ["SDL_VIDEODRIVER"] = "dummy"

n_hidden_neurons = 10

experiment_name = 'multi_demo'
if not os.path.exists(experiment_name):
    os.makedirs(experiment_name)

# initializes simulation in multi evolution mode, for multiple static enemies.
env = Environment(experiment_name=experiment_name,
                  enemies=[7,8],
                  multiplemode="yes",
                  playermode="ai",
                  player_controller=player_controller(n_hidden_neurons),
                  enemymode="static",
                  level=2,
                  speed="fastest",
                  visuals=False)

# default environment fitness is assumed for experiment

env.state_to_log() # checks environment state



MESSAGE: Pygame initialized for simulation.

########## Simulation state - INI ###########

# solutions # : EMPTY 

# sensors # : 20

 ------  parameters ------  

# contact hurt (training agent) # : player

multiple mode: yes

enemies list: 7 8

current enemy: 7

player mode: ai

enemy mode: static

level: 2

clock precision: low

inputs coded: no

random initialization: no

expiration time: 3000

speed: fastest

load player: yes

load enemy: yes

sound: off

overture time: 100

logs: on

save logs: yes

########## Simulation state - END ###########


In [3]:
####   Optimization for controller solution (best genotype-weights for phenotype-network): Ganetic Algorihm    ###

ini = time.time()  # sets time marker


# genetic algorithm params

run_mode = 'train' # train or test

# number of weights for multilayer with 10 hidden neurons.
n_vars = (env.get_num_sensors()+1)*n_hidden_neurons + (n_hidden_neurons+1)*5

dom_u = 1
dom_l = -1
npop = 100
gens = 30
mutation = 0.2
last_best = 0

np.random.seed(420)

In [4]:
# runs simulation
def simulation(env,x):
    f,p,e,t = env.play(pcont=x)
    return f

# normalizes
def norm(x,pfit_pop):

    if ( max(pfit_pop) - min(pfit_pop) ) > 0:
        x_norm = ( x - min(pfit_pop) )/( max(pfit_pop) - min(pfit_pop) )
    else:
        x_norm = 0

    if x_norm <= 0:
        x_norm = 0.0000000001
    return x_norm


# evaluation
def evaluate(x):
    return np.array(list(map(lambda y: simulation(env,y), x)))


# tournament
def tournament(pop):
    c1 =  np.random.randint(0,pop.shape[0], 1)
    c2 =  np.random.randint(0,pop.shape[0], 1)

    if fit_pop[c1] > fit_pop[c2]:
        return pop[c1][0]
    else:
        return pop[c2][0]


# limits
def limits(x):

    if x>dom_u:
        return dom_u
    elif x<dom_l:
        return dom_l
    else:
        return x


# crossover
def crossover(pop):

    total_offspring = np.zeros((0,n_vars))


    for p in range(0,pop.shape[0], 2):
        p1 = tournament(pop)
        p2 = tournament(pop)

        n_offspring = np.random.randint(1,3+1, 1)[0]
        offspring = np.zeros( (n_offspring, n_vars) )

        for f in range(0,n_offspring):
            # crossover
            cross_prop = np.random.uniform(0,1)
            offspring[f] = p1*cross_prop+p2*(1-cross_prop)

            # mutation
            for i in range(0,len(offspring[f])):
                if np.random.uniform(0 ,1)<=mutation:
                    offspring[f][i] =   offspring[f][i]+np.random.normal(0, 1)

            offspring[f] = np.array(list(map(lambda y: limits(y), offspring[f])))

            total_offspring = np.vstack((total_offspring, offspring[f]))

    return total_offspring


In [5]:
def arithmetic(p1, p2, a, p_left=0.5):
    
    child = np.repeat(-1, len(p1)).tolist()
    if np.random.uniform() < p_left:  # recombine left part
        child[:a] = 
        
    else: 
        child[:a] = 

SyntaxError: invalid syntax (3208107411.py, line 5)

In [107]:
def crossover(pop, fixed_start=True, fixed_end=True, p_left=0.5, p_mutation = 0.2):
    
    # for p in range(0, pop.shape[0], 2):  # stepsize 2, since you choose 2 parents and otherwise you get 2 times the number of offspring
        parents = np.zeros((2, pop.shape[1]))
        parents[0] = parent_selection(pop)
        parents[1] = parent_selection(pop)
        
        index_list = np.arange(0, len(parents[0])).tolist() #create a list of index to sample from
    
        if fixed_start:
            index_list.remove(0) #Remove the first index 0 from the list
    
        if fixed_end:
            index_list.remove(len(parents[0])-1) #Remove the last index from the list
        
        #Sample one integers from the index list
        a = random.choice(index_list)

        offspring = np.zeros((2, len(parents[0])))
        
        for c in range(len(offspring)):
            if np.random.uniform() <= p_left:  # recombine left part
                offspring[c, a:] = parents[c, a:]
                offspring[c, :a] = (parents[0, :a] + parents[1, :a]) / 2

            else:  # recombine right part
                offspring[c, :a] = parents[c, :a]
                offspring[c, a:] = (parents[c, a:] + parents[1, a:]) / 2
                
            # mutation 
            for i in range(len(offspring[c])):
                if np.random.uniform(0,1) <= p_mutation:
                    offspring[c, i] = np.random.uniform(-1, 1)
            
        return offspring
        

In [106]:
pop = np.random.uniform(0, 10, (2, 10))

crossover(pop)

NameError: name 'parent_selection' is not defined

In [104]:
pop

array([[3.06015298, 1.66821339, 4.66808693, 3.40878794, 4.11667637,
        0.91739448, 2.69653671, 5.28314435, 0.23078952, 3.33272517],
       [3.00198927, 0.46522647, 8.87099956, 4.39127688, 8.62884024,
        5.85548649, 4.0021702 , 9.30480571, 7.77376562, 2.96737497]])

In [99]:

p_left = 1
parents = np.zeros((2, pop.shape[1]))
parents[0] = pop[0]
parents[1] = pop[1]
        
index_list = np.arange(0, len(parents[0])).tolist() #create a list of index to sample from
        
#Sample two integers from the index list
a = random.choice(index_list)
        
child_1 = np.repeat(-1, len(parents[0])).tolist()
child_2 = np.repeat(-1, len(parents[0])).tolist()
offspring = np.zeros((2, len(parents[0])))
        
for c in range(len(offspring)):
    if np.random.uniform() < p_left:  # recombine left part
        offspring[c, a:] = parents[c, a:]
        offspring[c, :a] = (parents[0, :a] + parents[1, :a]) / 2

In [98]:
pop

array([[3.78161149, 4.48499313, 9.69531628, 9.79816561, 1.87038109,
        8.91605203, 5.87779712, 8.1830603 , 5.21240831, 1.83093754],
       [5.47921419, 0.82490476, 6.88085331, 4.19276304, 2.050734  ,
        3.85385955, 1.71417053, 4.26157424, 7.24275299, 6.10782156]])

In [31]:
child_1 = np.repeat(-1, len(p1)).tolist()
child_2 = np.repeat(-1, len(p1)).tolist()
child_1[:a] = p1[:a]
child_2[a:] = p1[a:]

In [43]:
pop = np.random.randint(0,10, (2, 10))
parents = np.zeros((2, pop.shape[1]))
parents[0, 5:] = pop[0, 5:]
parents[1] = pop[1]

In [44]:
parents

array([[0., 0., 0., 0., 0., 1., 4., 0., 4., 8.],
       [7., 9., 1., 1., 9., 5., 5., 8., 9., 6.]])